packages:
  - clients/js
  - clients/js/type-only-test
  - contracts
  - examples/hardhat
  - examples/hardhat-boilerplate
  - examples/hardhat-boilerplate/frontend
  - examples/truffle
  - integrations/hardhat
